### ISSUE TITLE
Denon AVR-X2400H not working

### ISSUE THREAD

**Issue by gielie** [dnpwwo/Domoticz-Denon-Plugin#1]
My new 2400H is not working properly, before i had an 2100 and this one worked fine.
The names of the different inputs have changed, how can i retrieve the different input names? especially internet radio.

**Comment by dnpwwo** [comment]
http://manuals.denon.com/AVRX2400H/EU/EN/GFNFSYicezyjvb.php#OKNRMLjzyiwmvh

Internet Radio looks like it is handled via HEOS which works differently.  Domoticz does support that as well, but this plugin does not

**Comment by devrosx** [comment]
hello, i also have Denon AVR-X2400H, on/off and volume works fine, but selector switch isnt working (dont care aboout inet radio). Any idea what should i check or add support in this script...

Jan
